// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Provides AI-powered suggestions for approvers based on a vague role title.
 *
 * - suggestApprovers - A function that suggests approvers based on a vague role title.
 * - SuggestApproversInput - The input type for the suggestApprovers function.
 * - SuggestApproversOutput - The return type for the suggestApprovers function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestApproversInputSchema = z.object({
  roleTitle: z.string().describe('The vague role title of the approver.'),
  employeeTitle: z.string().describe('The employee requesting leave their job title.'),
  teamMembership: z.string().describe('The team membership of the employee.'),
});
export type SuggestApproversInput = z.infer<typeof SuggestApproversInputSchema>;

const SuggestApproversOutputSchema = z.object({
  suggestedApprovers: z.array(z.string()).describe('A list of suggested approvers based on the role title, employee title, and team membership.'),
});
export type SuggestApproversOutput = z.infer<typeof SuggestApproversOutputSchema>;

export async function suggestApprovers(input: SuggestApproversInput): Promise<SuggestApproversOutput> {
  return suggestApproversFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestApproversPrompt',
  input: {schema: SuggestApproversInputSchema},
  output: {schema: SuggestApproversOutputSchema},
  prompt: `You are an AI assistant helping to suggest approvers for leave requests.

  Based on the employee's role, team membership, and the vague role title provided for the approver, suggest a list of potential approvers. Respond with specific employee names, not vague role titles.

  Employee Role: {{{employeeTitle}}}
  Team Membership: {{{teamMembership}}}
  Approver Role Title: {{{roleTitle}}}

  Suggest a list of approvers:
  `,
});

const suggestApproversFlow = ai.defineFlow(
  {
    name: 'suggestApproversFlow',
    inputSchema: SuggestApproversInputSchema,
    outputSchema: SuggestApproversOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
