
import type { Employee, LeaveRequest, LeaveType } from "@/types";
import { Briefcase, Heart, Plane, Baby } from "lucide-react";

export const initialEmployees: Employee[] = [
  {
    id: 1,
    name: "Alice Johnson",
    title: "Software Engineer",
    team: "Product Development",
    avatar: "https://placehold.co/40x40.png",
    supervisorId: 2,
    role: "Employee",
    contractType: "Full-time",
    contractStartDate: new Date("2022-01-15"),
    contractEndDate: null,
  },
  {
    id: 2,
    name: "Bob Williams",
    title: "Engineering Manager",
    team: "Product Development",
    avatar: "https://placehold.co/40x40.png",
    supervisorId: 3,
    role: "Supervisor",
    contractType: "Full-time",
    contractStartDate: new Date("2020-03-01"),
    contractEndDate: null,
  },
  {
    id: 3,
    name: "Charlie Brown",
    title: "Director of Engineering",
    team: "Management",
    avatar: "https://placehold.co/40x40.png",
    supervisorId: null,
    role: "Manager",
    contractType: "Full-time",
    contractStartDate: new Date("2018-07-20"),
    contractEndDate: null,
  },
    {
    id: 4,
    name: "Diana Prince",
    title: "HR Manager",
    team: "Human Resources",
    avatar: "https://placehold.co/40x40.png",
    supervisorId: 3,
    role: "Supervisor",
    contractType: "Full-time",
    contractStartDate: new Date("2021-09-01"),
    contractEndDate: null,
  },
  {
    id: 5,
    name: "Ethan Hunt",
    title: "Lead Designer",
    team: "Design",
    avatar: "https://placehold.co/40x40.png",
    supervisorId: 2,
    role: "Employee",
    contractType: "Contract",
    contractStartDate: new Date("2023-05-10"),
    contractEndDate: new Date("2024-11-10"),
  }
];

export const leaveTypes: LeaveType[] = [
  { id: 1, name: "Annual", icon: Plane },
  { id: 2, name: "Sick", icon: Heart },
  { id: 3, name: "Paternity", icon: Baby },
  { id: 4, name: "Unpaid", icon: Briefcase },
];

export const initialLeaveRequests: LeaveRequest[] = [
  {
    id: 1,
    employeeId: 1,
    leaveTypeId: 1,
    startDate: new Date("2024-08-10"),
    endDate: new Date("2024-08-15"),
    status: "Approved",
    supervisorReason: "Enjoy your vacation!",
    managerReason: "Approved.",
    approver: "Bob Williams",
  },
  {
    id: 2,
    employeeId: 5,
    leaveTypeId: 2,
    startDate: new Date("2024-07-22"),
    endDate: new Date("2024-07-23"),
    status: "Pending Manager",
    supervisorReason: "Approved, feel better soon.",
    managerReason: "",
    approver: "Bob Williams",
  },
  {
    id: 3,
    employeeId: 1,
    leaveTypeId: 3,
    startDate: new Date("2024-09-01"),
    endDate: new Date("2024-09-14"),
    status: "Pending Supervisor",
    supervisorReason: "",
    managerReason: "",
    approver: "Bob Williams",
  },
  {
    id: 4,
    employeeId: 5,
    leaveTypeId: 1,
    startDate: new Date("2024-12-20"),
    endDate: new Date("2024-12-28"),
    status: "Rejected",
    supervisorReason: "Project deadline conflict. Please reschedule.",
    managerReason: "",
    approver: "Bob Williams",
  },
];
