trigger:
- build

pool:
  name: eShopOnWebSelfPool

container:
  image: node:22-bullseye

steps:
- checkout: self

- script: |
    yarn install --frozen-lockfile
    yarn build
  displayName: Build Next.js in container
